### ISSUE TITLE
我要加功能

### ISSUE THREAD

**Issue by silica-github** [409915016/duel-living#1]
by 芒果

**Comment by silica-github** [comment]
玩涅普，唔加了，再见。

**Comment by PIK4** [comment]
救世啊

**Comment by silica-github** [comment]
> 救世啊

你识唔识加单元测试啊

![Nepgear](https://vignette.wikia.nocookie.net/hyperdimensionneptunia/images/4/45/NepgearV.png/revision/latest?cb=20151120234129 "Nepgear")
